image: node:latest

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

stages:
    - test
    - production

test:
    stage: test
    services:
        - mongo:latest
    script:
        - npm i npm@latest -g
        - npm i
        - npm test
    variables:
        mongoURI: "mongodb://mongo/heartbeat-app"
        NODE_ENV: "production"

production:
    type: deploy
    stage: production
    image: ruby:latest
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
    only:
        - master
