export const GET_REVIEW_SONG = 'GET_REVIEW_SONG';
export const REVIEW_SONG_LOADING = 'REVIEW_SONG_LOADING';

export const PLAYER_TOGGLE_PLAY = 'PLAYER_TOGGLE_PLAY';
export const PLAYER_TOGGLE_SEEK = 'PLAYER_TOGGLE_SEEK';
export const CHANGE_DURATION = 'CHANGE_DURATION';
export const CHANGE_CURRENTTIME = 'CHANGE_CURRENTTIME';

export const USER_LOADED = 'USER_LOADED';
export const USER_LOADING = 'USER_LOADING';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';